name: profil
description: A new Flutter project.

version: 1.0.0+1

environment:
  sdk: ">=2.19.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.2

flutter:
  uses-material-design: true
  assets:
    - assets/images/user-usercircle.png
    - assets/images/navigation-house01.png
    - assets/images/interface-bookopen.png
    - assets/images/interface-handbag.png
    - assets/images/interface-book-kky.png
    - assets/images/menu-morevertical.png
  #  - images/a_dot_ham.jpeg
  fonts:
    - family: LibreBodoni
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schylzer-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
